### ISSUE TITLE
Problem with creation subfolder in Android Device

### ISSUE THREAD

**Issue by PasqualeLanzieri** [coronalabs/com.coronalabs-plugin.zip#3]
Hi,
I use solar2d v. 3674,
every month I release an app containing a small website with its subfolders. This month I compiled the app, as always, but the site view goes into error no longer viewing the contents of the folders (images / logo.png example): debugging the code I saw that the subfolders in the zip file are not created in the documentsDirectory of the device.
1 - I have a zip file containing the miniSite, with the subfolders
2 - In buildSetting there is the plugin declaration
3 - It always worked great up to 15 days ago

On iOS version all ok
On Android make this error

Some idea?

All the best
Pasquale

**Comment by PasqualeLanzieri** [comment]
Hi,
is there a way to go back to a previous version of the plugin?

Kind Regards
Pasquale

**Comment by Shchvova** [comment]
Hello! I just updated Android part of the plugin building it with old toolchain. Please, verify if it helped your. Update should be live now.

**Comment by PasqualeLanzieri** [comment]
Yes! Thanks for your quick fix. All the Best, Pasquale
